"use client"

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import {
  Bar,
  BarChart,
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
  Cell,
} from "recharts"
import { useTheme } from "next-themes"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"
import { Users, TrendingUp, Activity, Stethoscope, FileText, Pill } from "lucide-react"

export function DoctorRevenueAnalytics() {
  const { theme } = useTheme()
  const isDark = theme === "dark"

  // Mock data for doctor revenue
  const revenueByDoctor = [
    { name: "Dr. James Ndiwa", value: 1250000, specialty: "Cardiology" },
    { name: "Dr. Sarah Wangui", value: 980000, specialty: "Pediatrics" },
    { name: "Dr. Michael Omondi", value: 1450000, specialty: "Orthopedics" },
    { name: "Dr. Emily Achieng", value: 1120000, specialty: "Gynecology" },
    { name: "Dr. David Kiprop", value: 1680000, specialty: "Neurology" },
  ]

  const revenueBySpecialty = [
    { name: "Cardiology", value: 1250000 },
    { name: "Pediatrics", value: 980000 },
    { name: "Orthopedics", value: 1450000 },
    { name: "Gynecology", value: 1120000 },
    { name: "Neurology", value: 1680000 },
  ]

  const monthlyRevenue = [
    { name: "Jan", revenue: 850000 },
    { name: "Feb", revenue: 920000 },
    { name: "Mar", revenue: 980000 },
    { name: "Apr", revenue: 1050000 },
    { name: "May", revenue: 1150000 },
    { name: "Jun", revenue: 1280000 },
  ]

  const patientThroughput = [
    { name: "Dr. James Ndiwa", registered: 85, completed: 65, specialty: "Cardiology" },
    { name: "Dr. Sarah Wangui", registered: 135, completed: 110, specialty: "Pediatrics" },
    { name: "Dr. Michael Omondi", registered: 72, completed: 58, specialty: "Orthopedics" },
    { name: "Dr. Emily Achieng", registered: 98, completed: 85, specialty: "Gynecology" },
    { name: "Dr. David Kiprop", registered: 52, completed: 42, specialty: "Neurology" },
  ]

  const patientThroughputByMonth = [
    { name: "Jan", registered: 120, completed: 95 },
    { name: "Feb", registered: 135, completed: 110 },
    { name: "Mar", registered: 145, completed: 120 },
    { name: "Apr", registered: 155, completed: 130 },
    { name: "May", registered: 170, completed: 145 },
    { name: "Jun", registered: 185, completed: 160 },
  ]

  const topProcedures = [
    { name: "Consultation", count: 320, revenue: 1120000 },
    { name: "Surgery", count: 85, revenue: 2550000 },
    { name: "Lab Tests", count: 210, revenue: 840000 },
    { name: "Imaging", count: 120, revenue: 960000 },
    { name: "Medication", count: 450, revenue: 1350000 },
  ]

  const COLORS = ["#0088FE", "#00C49F", "#FFBB28", "#FF8042", "#8884d8", "#82ca9d"]

  const formatCurrency = (value: number) => {
    return new Intl.NumberFormat("en-KE", {
      style: "currency",
      currency: "KES",
      minimumFractionDigits: 0,
      maximumFractionDigits: 0,
    }).format(value)
  }

  return (
    <div className="space-y-6">
      <Tabs defaultValue="revenue" className="w-full">
        <TabsList className="grid w-full grid-cols-3">
          <TabsTrigger value="revenue">Revenue Analysis</TabsTrigger>
          <TabsTrigger value="throughput">Patient Throughput</TabsTrigger>
          <TabsTrigger value="procedures">Procedures & Services</TabsTrigger>
        </TabsList>

        <TabsContent value="revenue" className="space-y-4 mt-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Card>
              <CardHeader>
                <CardTitle>Revenue by Doctor</CardTitle>
                <CardDescription>Total revenue generated by each doctor</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="h-[400px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart
                      data={revenueByDoctor}
                      layout="vertical"
                      margin={{ top: 20, right: 30, left: 40, bottom: 5 }}
                    >
                      <CartesianGrid strokeDasharray="3 3" stroke={isDark ? "#333" : "#eee"} />
                      <XAxis
                        type="number"
                        stroke={isDark ? "#888" : "#333"}
                        tick={{ fill: isDark ? "#888" : "#333" }}
                        tickFormatter={(value) => `KES ${value / 1000}k`}
                      />
                      <YAxis
                        dataKey="name"
                        type="category"
                        stroke={isDark ? "#888" : "#333"}
                        tick={{ fill: isDark ? "#888" : "#333" }}
                        width={120}
                      />
                      <Tooltip
                        contentStyle={{
                          backgroundColor: isDark ? "#1f2937" : "#fff",
                          color: isDark ? "#fff" : "#000",
                          border: `1px solid ${isDark ? "#374151" : "#e5e7eb"}`,
                        }}
                        formatter={(value) => [formatCurrency(value as number), "Revenue"]}
                      />
                      <Bar dataKey="value" fill="#3b82f6" radius={[0, 4, 4, 0]} />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Revenue by Specialty</CardTitle>
                <CardDescription>Distribution of revenue across medical specialties</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="h-[400px] flex items-center justify-center">
                  <ResponsiveContainer width="100%" height="100%">
                    <PieChart>
                      <Pie
                        data={revenueBySpecialty}
                        cx="50%"
                        cy="50%"
                        labelLine={true}
                        outerRadius={150}
                        fill="#8884d8"
                        dataKey="value"
                        label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                      >
                        {revenueBySpecialty.map((entry, index) => (
                          <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                        ))}
                      </Pie>
                      <Tooltip
                        contentStyle={{
                          backgroundColor: isDark ? "#1f2937" : "#fff",
                          color: isDark ? "#fff" : "#000",
                          border: `1px solid ${isDark ? "#374151" : "#e5e7eb"}`,
                        }}
                        formatter={(value) => [formatCurrency(value as number), "Revenue"]}
                      />
                    </PieChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>
          </div>

          <Card>
            <CardHeader>
              <CardTitle>Monthly Revenue Trend</CardTitle>
              <CardDescription>Revenue trend over the past 6 months</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="h-[300px]">
                <ResponsiveContainer width="100%" height="100%">
                  <LineChart data={monthlyRevenue}>
                    <CartesianGrid strokeDasharray="3 3" stroke={isDark ? "#333" : "#eee"} />
                    <XAxis dataKey="name" stroke={isDark ? "#888" : "#333"} tick={{ fill: isDark ? "#888" : "#333" }} />
                    <YAxis
                      stroke={isDark ? "#888" : "#333"}
                      tick={{ fill: isDark ? "#888" : "#333" }}
                      tickFormatter={(value) => `KES ${value / 1000}k`}
                    />
                    <Tooltip
                      contentStyle={{
                        backgroundColor: isDark ? "#1f2937" : "#fff",
                        color: isDark ? "#fff" : "#000",
                        border: `1px solid ${isDark ? "#374151" : "#e5e7eb"}`,
                      }}
                      formatter={(value) => [formatCurrency(value as number), "Revenue"]}
                    />
                    <Legend />
                    <Line type="monotone" dataKey="revenue" stroke="#3b82f6" strokeWidth={2} dot={{ r: 4 }} />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Card>
              <CardHeader>
                <CardTitle>Top Revenue Generators</CardTitle>
                <CardDescription>Doctors with highest revenue contribution</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {revenueByDoctor
                    .sort((a, b) => b.value - a.value)
                    .slice(0, 5)
                    .map((doctor, index) => (
                      <div key={index} className="space-y-2">
                        <div className="flex justify-between items-center">
                          <div className="flex items-center">
                            <div className="bg-primary text-primary-foreground w-5 h-5 rounded-full flex items-center justify-center text-xs mr-2">
                              {index + 1}
                            </div>
                            <div>
                              <div className="font-medium">{doctor.name}</div>
                              <div className="text-xs text-muted-foreground">{doctor.specialty}</div>
                            </div>
                          </div>
                          <div className="font-medium">{formatCurrency(doctor.value)}</div>
                        </div>
                        <Progress value={(doctor.value / revenueByDoctor[0].value) * 100} className="h-2" />
                      </div>
                    ))}
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Revenue Distribution</CardTitle>
                <CardDescription>Breakdown of revenue allocation</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-6">
                  <div className="grid grid-cols-3 gap-4">
                    <div className="flex flex-col items-center justify-center p-4 bg-muted rounded-lg">
                      <div className="text-xs text-muted-foreground mb-1">Hospital</div>
                      <div className="text-xl font-bold">30%</div>
                      <div className="text-sm">{formatCurrency(6480000 * 0.3)}</div>
                    </div>
                    <div className="flex flex-col items-center justify-center p-4 bg-muted rounded-lg">
                      <div className="text-xs text-muted-foreground mb-1">KRA</div>
                      <div className="text-xl font-bold">5%</div>
                      <div className="text-sm">{formatCurrency(6480000 * 0.05)}</div>
                    </div>
                    <div className="flex flex-col items-center justify-center p-4 bg-muted rounded-lg">
                      <div className="text-xs text-muted-foreground mb-1">Doctors</div>
                      <div className="text-xl font-bold">70%</div>
                      <div className="text-sm">{formatCurrency(6480000 * 0.7)}</div>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <div className="flex justify-between items-center">
                      <div className="font-medium">Hospital Share (30%)</div>
                      <div>{formatCurrency(6480000 * 0.3)}</div>
                    </div>
                    <div className="h-2 bg-muted rounded-full overflow-hidden">
                      <div className="h-full bg-primary rounded-full" style={{ width: "30%" }}></div>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <div className="flex justify-between items-center">
                      <div className="font-medium">KRA Share (5%)</div>
                      <div>{formatCurrency(6480000 * 0.05)}</div>
                    </div>
                    <div className="h-2 bg-muted rounded-full overflow-hidden">
                      <div className="h-full bg-amber-500 rounded-full" style={{ width: "5%" }}></div>
                    </div>
                  </div>

                  <div className="space-y-2">
                    <div className="flex justify-between items-center">
                      <div className="font-medium">Doctors Share (70%)</div>
                      <div>{formatCurrency(6480000 * 0.7)}</div>
                    </div>
                    <div className="h-2 bg-muted rounded-full overflow-hidden">
                      <div className="h-full bg-green-500 rounded-full" style={{ width: "70%" }}></div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        <TabsContent value="throughput" className="space-y-4 mt-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Card>
              <CardHeader>
                <CardTitle>Patient Throughput by Doctor</CardTitle>
                <CardDescription>Registered vs. completed treatment patients</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="h-[400px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={patientThroughput} margin={{ top: 20, right: 30, left: 40, bottom: 5 }}>
                      <CartesianGrid strokeDasharray="3 3" stroke={isDark ? "#333" : "#eee"} />
                      <XAxis
                        dataKey="name"
                        stroke={isDark ? "#888" : "#333"}
                        tick={{ fill: isDark ? "#888" : "#333" }}
                      />
                      <YAxis stroke={isDark ? "#888" : "#333"} tick={{ fill: isDark ? "#888" : "#333" }} />
                      <Tooltip
                        contentStyle={{
                          backgroundColor: isDark ? "#1f2937" : "#fff",
                          color: isDark ? "#fff" : "#000",
                          border: `1px solid ${isDark ? "#374151" : "#e5e7eb"}`,
                        }}
                      />
                      <Legend />
                      <Bar dataKey="registered" fill="#3b82f6" name="Registered Patients" />
                      <Bar dataKey="completed" fill="#10b981" name="Completed Treatment" />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Monthly Patient Throughput</CardTitle>
                <CardDescription>Patient flow trend over the past 6 months</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="h-[400px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <LineChart data={patientThroughputByMonth}>
                      <CartesianGrid strokeDasharray="3 3" stroke={isDark ? "#333" : "#eee"} />
                      <XAxis
                        dataKey="name"
                        stroke={isDark ? "#888" : "#333"}
                        tick={{ fill: isDark ? "#888" : "#333" }}
                      />
                      <YAxis stroke={isDark ? "#888" : "#333"} tick={{ fill: isDark ? "#888" : "#333" }} />
                      <Tooltip
                        contentStyle={{
                          backgroundColor: isDark ? "#1f2937" : "#fff",
                          color: isDark ? "#fff" : "#000",
                          border: `1px solid ${isDark ? "#374151" : "#e5e7eb"}`,
                        }}
                      />
                      <Legend />
                      <Line type="monotone" dataKey="registered" stroke="#3b82f6" name="Registered Patients" />
                      <Line type="monotone" dataKey="completed" stroke="#10b981" name="Completed Treatment" />
                    </LineChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>
          </div>

          <Card>
            <CardHeader>
              <CardTitle>Patient Completion Rate</CardTitle>
              <CardDescription>Percentage of patients who completed full treatment cycle</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
                  {patientThroughput.map((doctor) => {
                    const completionRate = Math.round((doctor.completed / doctor.registered) * 100)
                    return (
                      <Card key={doctor.name}>
                        <CardContent className="p-4">
                          <div className="text-center mb-2">
                            <div className="font-medium truncate">{doctor.name}</div>
                            <div className="text-xs text-muted-foreground">{doctor.specialty}</div>
                          </div>
                          <div className="flex justify-center">
                            <div className="relative w-20 h-20 flex items-center justify-center">
                              <svg className="w-20 h-20" viewBox="0 0 100 100">
                                <circle
                                  className="text-muted stroke-current"
                                  strokeWidth="10"
                                  cx="50"
                                  cy="50"
                                  r="40"
                                  fill="transparent"
                                ></circle>
                                <circle
                                  className="text-primary stroke-current"
                                  strokeWidth="10"
                                  strokeLinecap="round"
                                  cx="50"
                                  cy="50"
                                  r="40"
                                  fill="transparent"
                                  strokeDasharray={`${completionRate * 2.51} 251.2`}
                                  strokeDashoffset="0"
                                  transform="rotate(-90 50 50)"
                                ></circle>
                              </svg>
                              <div className="absolute text-center">
                                <div className="text-xl font-bold">{completionRate}%</div>
                              </div>
                            </div>
                          </div>
                          <div className="text-center mt-2 text-xs text-muted-foreground">
                            {doctor.completed} of {doctor.registered} patients
                          </div>
                        </CardContent>
                      </Card>
                    )
                  })}
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="procedures" className="space-y-4 mt-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Card>
              <CardHeader>
                <CardTitle>Top Procedures by Revenue</CardTitle>
                <CardDescription>Procedures generating the most revenue</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="h-[400px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={topProcedures} margin={{ top: 20, right: 30, left: 40, bottom: 5 }}>
                      <CartesianGrid strokeDasharray="3 3" stroke={isDark ? "#333" : "#eee"} />
                      <XAxis
                        dataKey="name"
                        stroke={isDark ? "#888" : "#333"}
                        tick={{ fill: isDark ? "#888" : "#333" }}
                      />
                      <YAxis
                        stroke={isDark ? "#888" : "#333"}
                        tick={{ fill: isDark ? "#888" : "#333" }}
                        tickFormatter={(value) => `KES ${value / 1000}k`}
                      />
                      <Tooltip
                        contentStyle={{
                          backgroundColor: isDark ? "#1f2937" : "#fff",
                          color: isDark ? "#fff" : "#000",
                          border: `1px solid ${isDark ? "#374151" : "#e5e7eb"}`,
                        }}
                        formatter={(value, name) => [
                          name === "revenue" ? formatCurrency(value as number) : value,
                          name === "revenue" ? "Revenue" : "Count",
                        ]}
                      />
                      <Legend />
                      <Bar dataKey="revenue" fill="#3b82f6" name="Revenue" />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader>
                <CardTitle>Top Procedures by Count</CardTitle>
                <CardDescription>Most frequently performed procedures</CardDescription>
              </CardHeader>
              <CardContent>
                <div className="h-[400px]">
                  <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={topProcedures} margin={{ top: 20, right: 30, left: 40, bottom: 5 }}>
                      <CartesianGrid strokeDasharray="3 3" stroke={isDark ? "#333" : "#eee"} />
                      <XAxis
                        dataKey="name"
                        stroke={isDark ? "#888" : "#333"}
                        tick={{ fill: isDark ? "#888" : "#333" }}
                      />
                      <YAxis stroke={isDark ? "#888" : "#333"} tick={{ fill: isDark ? "#888" : "#333" }} />
                      <Tooltip
                        contentStyle={{
                          backgroundColor: isDark ? "#1f2937" : "#fff",
                          color: isDark ? "#fff" : "#000",
                          border: `1px solid ${isDark ? "#374151" : "#e5e7eb"}`,
                        }}
                      />
                      <Legend />
                      <Bar dataKey="count" fill="#10b981" name="Procedure Count" />
                    </BarChart>
                  </ResponsiveContainer>
                </div>
              </CardContent>
            </Card>
          </div>

          <Card>
            <CardHeader>
              <CardTitle>Procedure Efficiency</CardTitle>
              <CardDescription>Revenue per procedure and frequency analysis</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-5 gap-4">
                  {topProcedures.map((procedure) => {
                    const revenuePerProcedure = procedure.revenue / procedure.count
                    return (
                      <Card key={procedure.name}>
                        <CardContent className="p-4">
                          <div className="flex items-center justify-center mb-2">
                            {procedure.name === "Consultation" && <Users className="h-8 w-8 text-primary" />}
                            {procedure.name === "Surgery" && <Stethoscope className="h-8 w-8 text-primary" />}
                            {procedure.name === "Lab Tests" && <Activity className="h-8 w-8 text-primary" />}
                            {procedure.name === "Imaging" && <FileText className="h-8 w-8 text-primary" />}
                            {procedure.name === "Medication" && <Pill className="h-8 w-8 text-primary" />}
                          </div>
                          <div className="text-center">
                            <div className="font-medium">{procedure.name}</div>
                            <div className="text-2xl font-bold mt-1">{formatCurrency(revenuePerProcedure)}</div>
                            <div className="text-xs text-muted-foreground">per procedure</div>
                            <div className="flex items-center justify-center mt-2">
                              <Badge variant="outline">{procedure.count} procedures</Badge>
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                    )
                  })}
                </div>

                <div className="space-y-4">
                  <h3 className="text-lg font-medium">Revenue to Procedure Count Ratio</h3>
                  <div className="space-y-2">
                    {topProcedures.map((procedure) => (
                      <div key={procedure.name} className="space-y-2">
                        <div className="flex justify-between items-center">
                          <div className="flex items-center">
                            <TrendingUp className="h-4 w-4 mr-2 text-muted-foreground" />
                            <span>{procedure.name}</span>
                          </div>
                          <div className="font-medium">{formatCurrency(procedure.revenue / procedure.count)}</div>
                        </div>
                        <Progress value={(procedure.revenue / procedure.count / 30000) * 100} className="h-2" />
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}
